/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeraaplicacioncs;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class frmejemplar extends javax.swing.JFrame {
private ejemplarBeans ejemplar;
    /**
     * Creates new form frmejemplar
     */
    public frmejemplar() {
        initComponents();
        try {
            ejemplar= new ejemplarBeans();
            cargarDatosComboBox();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        localizacion = new javax.swing.JLabel();
        idLibro = new javax.swing.JLabel();
        idEjemplar = new javax.swing.JLabel();
        txtidejemplar = new javax.swing.JTextField();
        txtidlibro = new javax.swing.JTextField();
        txtlocalizacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        itemejemplar = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtejemplar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 205, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("ejemplarBeans");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, 30));

        localizacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        localizacion.setText("localizacion");
        jPanel1.add(localizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 40));

        idLibro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idLibro.setText("idLibro");
        jPanel1.add(idLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        idEjemplar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idEjemplar.setText("idEjemplar");
        jPanel1.add(idEjemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        txtidejemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidejemplarActionPerformed(evt);
            }
        });
        jPanel1.add(txtidejemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, 20));

        txtidlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidlibroActionPerformed(evt);
            }
        });
        jPanel1.add(txtidlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, 20));
        jPanel1.add(txtlocalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 90, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jButton5.setForeground(new java.awt.Color(0, 51, 255));
        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        itemejemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemejemplarActionPerformed(evt);
            }
        });
        jPanel1.add(itemejemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jtejemplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idEjemplar", "idLibro", "localizacion"
            }
        ));
        jtejemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtejemplarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtejemplar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 320, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidejemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidejemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidejemplarActionPerformed

    private void txtidlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidlibroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.Actualizar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.Eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ingresofrm in =new ingresofrm();
        this.setVisible(false);
        in.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void itemejemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemejemplarActionPerformed
        // TODO add your handling code here:
      
        int IdEjemplar = Integer.parseInt(itemejemplar.getSelectedItem().toString());
        mostrarDatosejemplarBeans(IdEjemplar);  
    }//GEN-LAST:event_itemejemplarActionPerformed

    private void jtejemplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtejemplarMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_jtejemplarMouseClicked
private void nuevo() {
        try {
            ejemplarBeans lb = new ejemplarBeans();
            txtidejemplar.setText("" + lb.Incremento_ejemplar());
            txtidlibro.setText("");
            txtlocalizacion.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..." + e.toString());
        }
    }
private void cargarDatosComboBox() {
        try {
            ResultSet rs = ejemplar.obtenerejemplar();
            itemejemplar.removeAllItems();
            while (rs.next()) {
                int idEjemplar = rs.getInt("idEjemplar");
                itemejemplar.addItem(String.valueOf(idEjemplar));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos del ComboBox: " + e.toString());
        }
    }

    private void mostrarDatosejemplarBeans(int idEjemplar) {
        try {
            ResultSet rs = ejemplar.obtenerejemplar(idEjemplar);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("idLibro");
            modelo.addColumn("localizacion");

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("idEjemplar"),
                    rs.getString("idLibro"),
                    rs.getString("localizacion"),     
                };
                modelo.addRow(fila);
            }

            jtejemplar.setModel(modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar los datos del ejemplar: " + e.toString());
        }
    }

    private void enviar() {
        try {
            ejemplarBeans ej = new ejemplarBeans();
            ej.setIdEjemplar(Integer.parseInt(txtidejemplar.getText()));
            ej.setIdLibro(Integer.parseInt (txtidlibro.getText()));
            ej.setLocalizacion(Integer.parseInt(txtlocalizacion.getText()));
            ej.Insertar_ejemplar();
            this.mostrar(jtejemplar, "select * from ejemplar");
            JOptionPane.showMessageDialog(null, "La informacion ha sido guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de transaccion RollBack..." + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            ejemplarBeans ej = new ejemplarBeans();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);
            rs = ej.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }

    private void MouseClick() {
        int fila=jtejemplar.getSelectedRow();
        txtidejemplar.setText(jtejemplar.getModel().getValueAt(fila, 0).toString());
        txtidlibro.setText(jtejemplar.getModel().getValueAt(fila, 1).toString());
        txtlocalizacion.setText(jtejemplar.getModel().getValueAt(fila, 2).toString()); 
    }
    
    private void Actualizar(){
        try{
            ejemplarBeans ej = new ejemplarBeans();
            ej.setIdEjemplar(Integer.parseInt(txtidejemplar.getText()));
            ej.setIdLibro(Integer.parseInt (txtidlibro.getText()));
            ej.setLocalizacion(Integer.parseInt(txtlocalizacion.getText()));
            ej.Actualizar_ejemplar();
            this.mostrar(jtejemplar, "select * from ejemplar");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de transicion ROliBack.." + e.toString());
        }
    }
    private void Eliminar(){
        try {
            ejemplarBeans ej = new ejemplarBeans();
            ej.setIdEjemplar(Integer.parseInt(txtidejemplar.getText()));
            ej.Eliminar_ejemplar();
            this.mostrar(jtejemplar, "select * from ejemplar");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de transicion ROliBack.." + e.toString());
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idEjemplar;
    private javax.swing.JLabel idLibro;
    private javax.swing.JComboBox<String> itemejemplar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtejemplar;
    private javax.swing.JLabel localizacion;
    private javax.swing.JTextField txtidejemplar;
    private javax.swing.JTextField txtidlibro;
    private javax.swing.JTextField txtlocalizacion;
    // End of variables declaration//GEN-END:variables
}
