/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeraaplicacioncs;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class frmusuario extends javax.swing.JFrame {
private usuarioBeans usuario;
    
    public frmusuario() {
        initComponents();
         try {
            usuario= new usuarioBeans();
            cargarDatosComboBox();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idUsuario = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txtidusuario = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtusuario = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        itemusuario = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("usuariosBeans");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        idUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idUsuario.setText("idUsuario");
        getContentPane().add(idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nombre.setText("nombre");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        telefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        telefono.setText("telefono");
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        direccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        direccion.setText("direccion");
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 200, -1));

        txtidusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtidusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, -1));

        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, -1));

        jtusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idUsuario", "nombre", "telefono", "direccion"
            }
        ));
        jtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtusuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtusuario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 294, 400, 90));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 255));
        jButton6.setText("Nuevo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 74, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 255));
        jButton7.setText("Enviar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 115, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 255));
        jButton8.setText("Actualizar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 156, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 255));
        jButton9.setText("Eliminar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 197, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 402, -1, -1));

        itemusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemusuarioMouseClicked(evt);
            }
        });
        itemusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(itemusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 254, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtidusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidusuarioActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.Actualizar();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.Eliminar();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ingresofrm in =new ingresofrm();
        this.setVisible(false);
        in.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtusuarioMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_jtusuarioMouseClicked

    private void itemusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemusuarioMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_itemusuarioMouseClicked

    private void itemusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemusuarioActionPerformed
        // TODO add your handling code here:
        int IdUsuario = Integer.parseInt(itemusuario.getSelectedItem().toString());
        mostrarDatosusuarioBeans(IdUsuario);  
    }//GEN-LAST:event_itemusuarioActionPerformed

    private void nuevo() {
        try {
            usuarioBeans ub = new usuarioBeans();
            txtidusuario.setText("" + ub.Incremento_usuario());
            txtnombre.setText("");
            txttelefono.setText("");
            txtdireccion.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..." + e.toString());
        }
    }
private void cargarDatosComboBox() {
        try {
            ResultSet rs = usuario.obtenerusuario();
            itemusuario.removeAllItems();
            while (rs.next()) {
                int idUsuario = rs.getInt("idUsuario");
                itemusuario.addItem(String.valueOf(idUsuario));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos del ComboBox: " + e.toString());
        }
    }

    private void mostrarDatosusuarioBeans(int idUsuario) {
        try {
            ResultSet rs = usuario.obtenerusuario(idUsuario);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("nombre");
            modelo.addColumn("telefono");
            modelo.addColumn("direccion");

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("idUsuario"),
                    rs.getString("nombre"),
                    rs.getString("telefono"),    
                    rs.getString("direccion"),
                };
                modelo.addRow(fila);
            }

            jtusuario.setModel(modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar los datos del usuario: " + e.toString());
        }
    }
    
    private void enviar() {
        try {
            usuarioBeans ub = new usuarioBeans();
            ub.setIdUsuario(Integer.parseInt(txtidusuario.getText()));
            ub.setNombre(txtnombre.getText());
            ub.setTelefono(Integer.parseInt(txttelefono.getText()));
            ub.setDireccion(txtdireccion.getText());

            ub.Insertar_usuario();
            this.mostrar(jtusuario, "select * from usuario");
            JOptionPane.showMessageDialog(null, "La informacion ha sido guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de transaccion RollBack..." + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            usuarioBeans ub = new usuarioBeans(); 
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);
            rs = ub.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }

    private void MouseClick() {
        int fila=jtusuario.getSelectedRow();
        txtidusuario.setText(jtusuario.getModel().getValueAt(fila, 0).toString());
        txtnombre.setText(jtusuario.getModel().getValueAt(fila, 1).toString());
        txttelefono.setText(jtusuario.getModel().getValueAt(fila, 2).toString());
        txtdireccion.setText(jtusuario.getModel().getValueAt(fila, 3).toString());

        
    }
    private void Actualizar(){
        try{
            usuarioBeans ub = new usuarioBeans();
            ub.setIdUsuario(Integer.parseInt(txtidusuario.getText()));
            ub.setNombre(txtnombre.getText());
            ub.setTelefono(Integer.parseInt(txttelefono.getText()));
            ub.setDireccion(txtdireccion.getText());
            
            ub.Actualizar_usuario();
            this.mostrar(jtusuario, "select * from usuario");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de transicion ROliBack.." + e.toString());
        }
    }
    private void Eliminar(){
        try {
            usuarioBeans ub = new usuarioBeans();
            ub.setIdUsuario(Integer.parseInt(txtidusuario.getText()));
            ub.Eliminar_usuario();
            this.mostrar(jtusuario, "select * from usuario");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de transicion ROliBack.." + e.toString());
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel idUsuario;
    private javax.swing.JComboBox<String> itemusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtusuario;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtidusuario;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
